### PR TITLE
[DO NOT MERGE] Generate reports

### PR DESCRIPTION
**Pull request by valdisxp1**
- Generates multiple charts and a report in markdown (md)
- Add command line arguments to both `run.py` and `summary.py`. This makes testing the performance of new features easier (see Readme.md).

See example report:
https://github.com/valdisxp1/scala-native-benchmark-results/blob/gh-pages/reports/summary_20180923_222231_scala-native-0.3.8_vs_scala-native-0.3.9-SNAPSHOT/Readme.md

### CODE REVIEW

**Comment by densh** [comment]
Version comparison is extremely valuable, well done!

The numbers look really srange though, 3-5x degradation from version to version looks like either debug mode or boehm gc.

**Comment by valdisxp1** [comment]
I will double-check that I do not have any debugging enabled by accident and re-run it tonight.

**Comment by densh** [comment]
@valdisxp1 Indeed, master regressed wrt 0.3.8. I did manual bisect based first few benchmarks  and found that it regressed in https://github.com/scala-native/scala-native/pull/1295. The issue is that we used to do DCE after lowering and before codegen and that PR mistakenly removed it.

**Comment by valdisxp1** [comment]
Including more changes #4 and automation stuff.
Comparing your changes against master is as easy as:
1. have `scala-native` and `scala-native-benchmarks` in the same parent directory
2. from scala-native-benchmarks
```bash
scripts/run.py latest@master latest@my-branch
scripts/summary latest@master latest@my-branch
```

**Comment by valdisxp1** [comment]
Splitting the code into smaller PRs and improving code quality.
#6 #7 
This branch has most of the things working, but the code is not clean or very readable.

**Pull request closed without merging**
